github: [metadata]
encoding: utf-8
markdown: redcarpet
highlighter: true
name: Yulong Yang
title: Yulong Yang
description: Yulong's personal site
url: https://yyl.github.io
theme: jekyll-theme-modernist
