github: [metadata]
encoding: utf-8
markdown: redcarpet
highlighter: rouge
title: Yulong Yang
description: A personal site
url: https://yulong.io
theme: minima
# disqus:
  # shortname: bytestoreality
show_excerpts: false
minima:
  social_links:
    github: yyl
    linkedin: yulongyang
    rss: rss
    stackoverflow: '723511'
plugins:
  - jekyll-seo-tag