github: [metadata]
encoding: utf-8
markdown: redcarpet
highlighter: true
title: Yulong Yang
email: yyl.dev@gmail.com
description: Yulong's personal siteeee
url: https://yyl.github.io
theme: minima
disqus:
  shortname: bytestoreality
show_excerpts: false
minima:
  social_links:
    twitter: jekyllrb
    github: jekyll