github: [metadata]
encoding: utf-8
markdown: redcarpet
highlighter: true
title: Yulong Yang
description: A personal site
url: https://yyl.github.io
theme: minima
disqus:
  shortname: bytestoreality
show_excerpts: false
minima:
  social_links:
    github: yyl